pipeline:
  name: Build netflixproject_project
  identifier: Build_gurutejdevops_netflixproject_project_1765487580837
  projectIdentifier: JavaCIProject
  orgIdentifier: default
  stages:
    - stage:
        name: Build Stage
        identifier: Build
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: |-
                      docker ps
                      docker version
                      docker images
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
        description: ""
