pipeline:
  name: Build netflixproject_project
  identifier: Build_gurutejdevops_netflixproject_project_1765487580837
  projectIdentifier: JavaCIProject
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1765487292951
        repoName: gurutejdevops/netflixproject_project
        build: <+input>
